folders:
  data: C:\Users\larue\OneDrive - Chapman University\Research\Methanol Decomposition\2022-Current
    Pt(111)\X-Ray Photoelectron Spectroscopy (XPS)\2022.07.06-11 SSRL
  figures: figures
  fits: fits
